url: https://example.com
visit_count: 5
interval: 5
browser: chrome
headless: true
auto_scroll: true
scroll_pause: 1.0
max_scroll: 3
random_delay: true
delay_range: [2, 8]
proxy: 127.0.0.1:8080
retry_attempts: 2
retry_delay: 3
log_level: DEBUG
log_file: visitor.log
log_rotate: true
max_log_size: 1MB
backup_count: 2
